### ISSUE TITLE
terminal multiplexers bypass remote sudo password

### ISSUE THREAD

**Issue by Fuseteam** [mcdope/pam_usb#51]
hi me again, thanks for recent update, i just happen to be running version 0.7.1 and version 0.7.3 at the same time, so I can confirm this bug also exists on version 0.7.1
basically the steps to reproduce it are these:
- ssh into a remote system
- run tmux/byobu
- run sudo su

deny remote is set to true and it indeed denies access outside of byobu, it also denies the 'cup of tee' access aswell in the case of 0.7.3(as expected), but inside of byobu or tmux it happily grants access

**Comment by mcdope** [comment]
Thanks for reporting!

I'm slightly irritated because we now walk the process hierarchy and as long sshd (or telnetd) is found in the parent chain it should be denied. I have the feeling it's somehow related to the detaching most multiplexers provide. In that case I could slap the previously used utmp check on it - i hope - to catch those cases. 
 
But well possible that we will have to accept that it either has some holes, or some cases where the auth fails incorrectly. Which would mean an option again :D 

Will investigate next week.

In case you're motivated to test some things: it would be interesting to see if `screen` is also affected (wanna bet yes). Also interesting would be the output with `debug` set to true globally (or per user).

**Comment by mcdope** [comment]
Note to myself: check if possible to find spawning process in case there is no parent found (or left)

**Comment by Fuseteam** [comment]
> Thanks for reporting!
> 
> I'm slightly irritated because we now walk the process hierarchy and as long sshd (or telnetd) is found in the parent chain it should be denied. I have the feeling it's somehow related to the detaching most multiplexers provide. In that case I could slap the previously used utmp check on it - i hope - to catch those cases.
> 
> But well possible that we will have to accept that it either has some holes, or some cases where the auth fails incorrectly. Which would mean an option again :D
> 
> Will investigate next week.
> 
> In case you're motivated to test some things: it would be interesting to see if `screen` is also affected (wanna bet yes). Also interesting would be the output with `debug` set to true globally (or per user).

haha yeah but considering it was also bypassed in version 0.7.1 i kinda doubt the utmp will help much

i will test screen for sure and i'll paste the output from debug true as soon as i got it x
D

**Comment by mcdope** [comment]
> haha yeah but considering it was also bypassed in version 0.7.1 i kinda doubt the utmp will help much

utmp wasn't used in default config because of "unknown_pts_as_local" (well, it was used - but a not-found resulted in "assume it will be local". 

That option was introduced with default=true because else i.e gdm3 fails to auth (at least on Ubuntu). But I have the hope that maybe a detached session (which I assume is the cause here) will get a proper utmp entry. In that case we could use the current approach, and if no remote daemon is found (like it seems in this case/issue) use utmp additionally to verify. 

Of course that requires that we have a proper utmp entry for that session, if not - get rekt. 

Which btw is another thing you could check if you want - after you used that bypass method you could run `w` to show active sessions. Would be interesting if there is a session for the bypass and if it shows an IP (or Hostname).

**Comment by Fuseteam** [comment]
sure no problem just checked out screen it is being denied xD
this the debug log for tmux:
```
* Authentication request for user "fuseteam" (sudo)                             
[src/local.c:033] Checking whether the caller is local or not...                
[src/local.c:039]     Checking pid  18382 (sudo)...                             
[src/local.c:039]     Checking pid  18106 (/bin/bash)...                        
[src/local.c:039]     Checking pid  13778 (tmux)...                             
[src/local.c:048] No remote daemons found in parent process list, seems to be lo
cal request - allowing.                                                         
[src/device.c:038] Searching for "fuseteam" in the hardware database...
* Authentication device "fuseteam" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid 1398-7F06.
[src/volume.c:121] Found mount points: /media/fuseteam/KINGSTON
[src/volume.c:134] Found volume 1398-7F06.
[src/volume.c:158] Volume 1398-7F06 is already mounted.
[src/pad.c:256] Loading device pad...
[src/pad.c:258] Loading system pad...
[src/pad.c:264] Pad match.
[src/pad.c:153] Checking whether pads are expired or not...
[src/pad.c:182] Pads were generated 2667 seconds ago, not updating.
* Access granted.
```
and here's the one for screen
```
* Authentication request for user "fuseteam" (sudo)
[src/local.c:033] Checking whether the caller is local or not...
[src/local.c:039]     Checking pid  24316 (sudo)...
[src/local.c:039]     Checking pid  24213 (/bin/bash)...
[src/local.c:039]     Checking pid  24212 (SCREEN)...
[src/local.c:039]     Checking pid  24211 (screen)...
[src/local.c:039]     Checking pid  15448 (-bash)...
[src/local.c:039]     Checking pid  15447 (sshd: fuseteam@pts/1)...
* One of the parent processes found to be a remote access daemon, denying.
* Access denied.
```

**Comment by mcdope** [comment]
Really surprised screen isn't affected. Interesting.

But for tmux the "utmp on top" approach would seem to work since there is clearly a remote session for it in utmp, that's nice to know.

**Comment by Fuseteam** [comment]
yeah i'm surprised by screen as well xD

**Comment by Fuseteam** [comment]
i did a couple more tests and it appears there's always 2 sessions for tmux/byobu in utmp when I'm ssh'ed in regardless whether I'm attached to the same session on both devices or not

**Comment by mcdope** [comment]
For the records: tmux having seemingly no parent process is explained here: https://superuser.com/a/1472783

**Comment by Fuseteam** [comment]
> For the records: tmux having seemingly no parent process is explained here: https://superuser.com/a/1472783

nice find!  based on this piece
> So the server gets PPID of 1 almost immediately. Every shell or another process you run within tmux is a descendant of the server. After you (re-)attach, you see what the client shows you. **The client itself is a child of the shell you invoked it in (or sshd or whatever). It talks to the server, passes keystrokes to it, receives information on how the window should look like and prints characters accordingly.**

bolding mine I suppose this means we're walking the process tree of the server rather of the client perhaps? :thinking:

**Comment by mcdope** [comment]
The issue is: trough this "Quake 3 like re-spawning" `tmux` isn't connected to the host process (sshd) anymore. So we can't detect it by the current "walk parents and check name" approach.

I'm right now working on an approach that still walks the process tree, but also checks if stdin of parent process is attached to a remote session in utmp. If this works like intended it would be "throwing a nuke onto cockroaches" and should solve all similar cases.

I've opened a local ssh session and ran `tmux` to verify with shell commands that my approach should work. One of `tmux`s file descriptors in proc (`/proc/<pid>/fd`) seems to always point to some pts (pseudo terminal). And that pts should be available with IP in utmp, at least according to `w`. So by simply walking `/proc/<pid>/fd` for symlinks pointing to /dev, then checking utmp for them it should be possible to reliable detect remote sessions. If this turns out to work like I suppose we can remove the name based code at all.

**Comment by Fuseteam** [comment]
cool that sounds like quite a robust approach, hopefully this hammers the hole shut once and for all

**Comment by mcdope** [comment]
Since tmux redirects stdin, stdout and stderr my planned approach isn't working.

Current new plan: understand the libprocps api and use it to get the tty of given process - which would work very likely. That's what's used by ps and top to get informations, including the correct tty. But that will take a while because I couldn't find a nice example of how to just get the info for a given pid :sweat_smile:

**Comment by Fuseteam** [comment]
yeah no problem, thanks for the update

**Comment by mcdope** [comment]
Know what, I hate tmux lol. Turn's out, my approach works nicely - but: we are running in the context of the server (in tmux terms), which yields the wrong tty, which again results in a non working check :facepalm: Still need to check if this also applies to byobu. 

But I've found that tmux sets an env var containing the client id, which again can be used with `tmux list-clients` to grep the correct tty which can the be used to check utmp for "remoteness" of the sesssion. You can run `CLIENTID=${TMUX: -1}; tmux list-clients | grep ": $CLIENTID \[" | awk 'BEGIN { FS = ":" } ; {print $1}'` under tmux to get your login tty as a POC. 

![image](https://user-images.githubusercontent.com/3312979/109391677-915e8980-7918-11eb-93e6-e26b5d70bbd4.png)


Of course this could be circumvented by just deleting or modifing that envvar. For that case I would fallback to denying the request. 

You happen to know any other multiplexers I should test?

**Comment by Fuseteam** [comment]
lol tmux does things quite weirdly, sadly I only know of byobu, tmux and screen, afaict byobu is just a front end for a terminal multiplexer. by default the backend  on ubuntuis tmux

**Comment by mcdope** [comment]
Oh that's nice to know, then I should check what backends it supports.

**Comment by Fuseteam** [comment]
hmm found a list of 7 terminal multiplexers: https://www.linuxlinks.com/terminalmultiplexers/ but I have a feeling the majority is just forked from tmux

**Comment by mcdope** [comment]
Local tmux (in bash, in terminator, under gnome-shell with gdm3): https://asciinema.org/a/4TYiAyxIAwUHt3AmGHqs5eGhw
Remote tmux (well, ssh to localhost): https://asciinema.org/a/ZonJgePgeGyHCFYv7ejwavzPD
Local bash (in clion, under gs/gdm again): https://asciinema.org/a/fIKFRFQkZDxAaQ0H86aO7v7Io
Local console tty: https://asciinema.org/a/C5dpgxYQke9z1sd5cdm7ysmJW

:grin:

**Comment by Fuseteam** [comment]
cool :star_struck: great work!

**Comment by mcdope** [comment]
https://asciinema.org/a/wyQypy8QXngPIQawoXfN2dCii

Seems to works fine. If you're brave enough, you can find a signed testing deb at https://www.dropbox.com/s/rdwwiskezx7en2g/libpam-usb_0.7.3_amd64.deb?dl=0. But be aware, I haven't even tested this myself yet except what you can see on the terminal capture.

**Comment by Fuseteam** [comment]
wooohooo imma download that as soon as I get home :3

**Comment by Fuseteam** [comment]
cool! so now if i can do ssh in and use byobu I'm denied on account that the tmux variable is not set
if I then detach and exit and open local terminal and attach to the same session the tmux variable is still not set so I'm still denied xD
interesting enough I do that in reverse i get no `utmp enty found for tty ":0"` and get denied too but if I drop to a tty i do get granted access :3

**Comment by mcdope** [comment]
Seems I broke graphical login managers, at least in GDM I can't login anymore as long as pam_usb is enabled :facepalm:

**Comment by mcdope** [comment]
Unrelated to the crash, it wouldn't work in GDM (or any other display manager I guess) anyway since there wont be a tty attached to it (which is what we had in #8). But this was to be expected, I just didn't thought about it.

Last time I just whitelisted unknown pts, but I would like to avoid that (always best to keep things tight). So I thought about whitelisting just display managers in the process chain. But for that I would need to check if XDMCP is enabled, because if it is - we definitely don't want to allow access. So I took a look at libxdmcp. Then I made sure to quickly look in another direction again because that lib is undocumented and impossible to understand. I even looked at implementations (i.e XDM), but seriously - that lib is from the second ring of hell - at least.

New plan: check how parse proc for open UDP ports of a given process, to check if login manager is listening on 117 (which is XDMCPs control port). (Yes, there is netstat etc - but I want to avoid additional dependencies, esp. if external)

Worst case fallback: just whitelist display managers. But that's a potential hole if someone is stupid enough to enable XDMCP. So I would like to avoid that if reasonable possible.

Random rant: I knew that coding X clients is a tricky mess from many articles over the years, but that lib... omg... There are copyright headers from when I was 4 years old -.- I would prefer to implement a HTML parser in brainfuck over ever touching X stuff.

**Comment by Fuseteam** [comment]
oh my goodness x really is a mess huh

**Comment by mcdope** [comment]
Status update: tried to connect to a maybe existing XDMCP server to make sure there is none, but: I've failed to setup XDMCP on my VM in the first place. And I won't release code I haven't tested. Since it's an ancient protocol that is insecure in itself I wont waste more time on XDMCP exclusion. Esp. since every pamusb version so far should be allowing XDMCP I guess. If someone is combining XDMCP with a PAM module to skip password authentication, no security check can help. (XDMCP is transferring everything unencrypted, auth, screen, inputs - literally everything)

I'm currently working on checking the service name provided by the caller (the process requesting a pam auth). By trusting that value we can whitelist gdm/lightdm/xdm etc. For console and virtual terminals we will use the current methods.

But I've already noticed a new problem while testing: on lightdm and xdm the DISPLAY approach isn't working because these two register a true tty as session device instead of DISPLAY like gdm :roll_eyes:. 

utmp is a serious mess, since every process can put whatever it wants. In fact, a login process could put "pinkunicorn" as tty and it would still be "valid" afaik. (You can see that on `w` after logging in by gdm, the field for idle time will have 'xdm' as value :facepalm: )

So I will have to whitelist graphical logins by their service tag and for everything else loop over all methods, tmux, display, tty and only deny if none of them confirmed a local user to not break sudo.

**Comment by mcdope** [comment]
With each step into this rabbithole of linux authentication I feel like I know nothing again :rofl: 

Remember the nicely working tmux approach? Well, try it if you're logged in using lightdm... :roll_eyes: If logged in with lightdm, running gnome-terminal, the tmux approach yields a pts that isn't registered in utmp. But: the tty returned by `ttyname()` is registered, which isn't the case when running in gnome-terminal when logged in with gdm. :exploding_head: 

I'm making progress, guess this will catch almost every case. But I guess we will never catch EVERY case. 

![Peek 2021-03-07 16-58](https://user-images.githubusercontent.com/3312979/110246119-89c96100-7f66-11eb-9cce-600ccedcb593.gif)

**Comment by Fuseteam** [comment]
yeah tis weird how this stuff works :rofl:

**Comment by mcdope** [comment]
Making quite some progress, scenarios tested and working now:

* local session, logged in by lightdm, gnome, user
* local session, logged in by lightdm, gnome, sudo
* local session, logged in by lightdm, gnome, user, tmux
* local session, logged in by lightdm, gnome, sudo, tmux
* ssh session (running in gnome @ lightdm, but shouldn't matter for remote), user
* ssh session (running in gnome @ lightdm, but shouldn't matter for remote), sudo
* ssh session (running in gnome @ lightdm, but shouldn't matter for remote), user, tmux
* ssh session (running in gnome @ lightdm, but shouldn't matter for remote), sudo, tmux

Gonna have to run the same on TTY, GDM, SDDM (used by Kubuntu) before I can release it. But if you're brave, compile the branch ;-)

**Comment by Fuseteam** [comment]
niiice imma try it as soon as I get the chance xD

**Comment by Fuseteam** [comment]
daaaaang

**Comment by mcdope** [comment]
Found a way to do it on SDDM too, a pretty effective too. I have the slight hope that with that method this is finally done, but we will see :D

**Comment by mcdope** [comment]
All 8 cases completed OK on XDM now too

![ssh-user-check-xdm-gnome-tmux](https://user-images.githubusercontent.com/3312979/110806757-a7f2d200-8282-11eb-9783-d9f094ccc773.png)
![local-user-check-xdm-gnome](https://user-images.githubusercontent.com/3312979/110806759-a88b6880-8282-11eb-9b0f-0bc36733d3b7.png)

**Comment by mcdope** [comment]
lmao, lxdm is quite a snowflake :rofl: No utmp entry at all XD No way I can get it to work there...

![grafik](https://user-images.githubusercontent.com/3312979/110807946-d4f3b480-8283-11eb-85a9-620e00516905.png)

**Comment by mcdope** [comment]
So I've now successfully tested TTY, GDM, LightDM, SDDM, XDM. LXDM is doing stupid things, so no support for that. I don't think there are any other major login managers left to test.

Will clean up the code, give it a review by myself and prepare a testing release.

**Comment by mcdope** [comment]
Here we go, signed testing deb available @ https://www.dropbox.com/sh/tyhij9dow0rezoo/AADaGc_iDQhqaJGNEF7oQspqa?dl=0 (together with proof-screenshots of my tests)

There is still some refactoring left before I will wrap up a proper release, but that's just about style - functionality is final.

**Comment by Fuseteam** [comment]
hehehehe sure will :3

**Comment by Fuseteam** [comment]
so i have some fun stuff for you both I ssh into byobu and I have an option terminal on my remote so like
- ssh remote -> byobu session
- on the remote machine launch terminal attach to byobu

and I get this xD:
```
* Authentication request for user "tk" (sudo)
[src/local.c:177] Checking whether the caller (sudo) is local or not...
[src/local.c:187]       Checking pid  32710 (sudo)...
[src/local.c:187]       Checking pid  32484 (/bin/bash)...
[src/local.c:187]       Checking pid  23762 (tmux)...
[src/local.c:190]               Setting pid 32484 as fallback for tmux check
[src/tmux.c:028]                No TMUX env var, checking parent process in case this is a sudo request
[src/tmux.c:040]                Got tmux_client_id: 5
[src/tmux.c:043]                Got tmux_socket_path: /tmp/tmux-1000/default
[src/tmux.c:047]                Built get_tmux_session_details_cmd: tmux -S /tmp/tmux-1000/default list-clients -t 5
can't find session 5
* tmux detected, but couldn't get client details. Denying since remote check impossible without it!
[src/local.c:253]       Using TTY /dev/pts/6 for search
[src/local.c:050]               utmp entry for tty "pts/6" found
[src/local.c:051]                       utmp->ut_pid: 23762
[src/local.c:052]                       utmp->ut_user: tk
[src/local.c:066]               Checking utmp->ut_addr_v6[0]
[src/local.c:066]               Checking utmp->ut_addr_v6[1]
[src/local.c:066]               Checking utmp->ut_addr_v6[2]
[src/local.c:066]               Checking utmp->ut_addr_v6[3]
[src/local.c:070]       utmp check successful, request originates from a local source!
[src/local.c:259] No remote access detected, seems to be local request - allowing.
[src/device.c:038] Searching for "fuseteam" in the hardware database...
* Authentication device "fuseteam" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid 67E3-17ED.
[src/volume.c:121] Found mount points: (null)
[src/volume.c:134] Found volume 67E3-17ED.
[src/volume.c:044] Attempting to mount device /dev/sdb1.
[src/volume.c:056] Mounted device /dev/sdb1 to /media/root/EFI.
[src/pad.c:256] Loading device pad...
[src/pad.c:258] Loading system pad...
[src/pad.c:264] Pad match.
[src/pad.c:153] Checking whether pads are expired or not...
[src/pad.c:182] Pads were generated 319 seconds ago, not updating.
[src/volume.c:183] Attempting to unmount /dev/sdb1 from /media/root/EFI.
[src/volume.c:194] Unmount succeeded.
* Access granted.
```

**Comment by mcdope** [comment]
Seems I've messed up an `if`, it shouldn't retry when "tmux validation" fails like it did here. 

Can you please provide a step-by-step guide to reproduce? I'm not familiar with byobu and would really help with testing.

**Comment by Fuseteam** [comment]
so i 
- pressed f1 
- enabled byobu at login 
- I ssh'ed in the machine
- ran sudo su

**Comment by Fuseteam** [comment]
man this thing is fickle i now have trouble reproducing the same log I now instead get this:
```
* Authentication request for user "tk" (sudo)
[src/local.c:177] Checking whether the caller (sudo) is local or not...
[src/local.c:187]       Checking pid   5450 (sudo)...
[src/local.c:187]       Checking pid   4411 (/bin/bash)...
[src/local.c:187]       Checking pid   4405 (tmux)...
[src/local.c:190]               Setting pid 4411 as fallback for tmux check
[src/tmux.c:028]                No TMUX env var, checking parent process in case this is a sudo request
[src/tmux.c:040]                Got tmux_client_id: 1
[src/tmux.c:043]                Got tmux_socket_path: /tmp/tmux-1000/default
[src/tmux.c:047]                Built get_tmux_session_details_cmd: tmux -S /tmp/tmux-1000/default list-clients -t 1
[src/tmux.c:060]                Got tmux_client_tty: pts/0
[src/local.c:047]       No utmp entry found for tty "pts/0"
[src/local.c:218]       Using DISPLAY :0 for utmp search
[src/local.c:047]       No utmp entry found for tty ":0"
[src/local.c:224]       Trying to get tty from Xorg process
[src/local.c:229]       Retrying with tty /dev/tty7, obtained from Xorg, for utmp search
[src/local.c:050]               utmp entry for tty "tty7" found
[src/local.c:051]                       utmp->ut_pid: 17674
[src/local.c:052]                       utmp->ut_user: tk
[src/local.c:066]               Checking utmp->ut_addr_v6[0]
[src/local.c:066]               Checking utmp->ut_addr_v6[1]
[src/local.c:066]               Checking utmp->ut_addr_v6[2]
[src/local.c:066]               Checking utmp->ut_addr_v6[3]
[src/local.c:070]       utmp check successful, request originates from a local source!
[src/local.c:259] No remote access detected, seems to be local request - allowing.
[src/device.c:038] Searching for "fuseteam" in the hardware database...
* Authentication device "fuseteam" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid 67E3-17ED.
[src/volume.c:121] Found mount points: (null)
[src/volume.c:134] Found volume 67E3-17ED.
[src/volume.c:044] Attempting to mount device /dev/sdb1.
[src/volume.c:056] Mounted device /dev/sdb1 to /media/root/EFI.
[src/pad.c:256] Loading device pad...
[src/pad.c:258] Loading system pad...
[src/pad.c:264] Pad match.
[src/pad.c:153] Checking whether pads are expired or not...
[src/pad.c:182] Pads were generated 940 seconds ago, not updating.
[src/volume.c:183] Attempting to unmount /dev/sdb1 from /media/root/EFI.
[src/volume.c:194] Unmount succeeded.
* Access granted.
```

**Comment by Fuseteam** [comment]
additionally if i 
- toggle byobu at login
- type exit to ensure all sessions are closed
- ssh into remote
I get this:
```
* Authentication request for user "tk" (sudo)
[src/local.c:177] Checking whether the caller (sudo) is local or not...
[src/local.c:187]       Checking pid  28131 (sudo)...
[src/local.c:187]       Checking pid  27801 (/bin/bash)...
[src/local.c:187]       Checking pid  26157 (tmux)...
[src/local.c:190]               Setting pid 27801 as fallback for tmux check
[src/tmux.c:028]                No TMUX env var, checking parent process in case this is a sudo request
[src/tmux.c:040]                Got tmux_client_id: 1
[src/tmux.c:043]                Got tmux_socket_path: /tmp/tmux-1000/default
[src/tmux.c:047]                Built get_tmux_session_details_cmd: tmux -S /tmp/tmux-1000/default list-c
lients -t 1
[src/tmux.c:060]                Got tmux_client_tty: pts/0
[src/local.c:050]               utmp entry for tty "pts/0" found
[src/local.c:051]                       utmp->ut_pid: 25972
[src/local.c:052]                       utmp->ut_user: tk
* Remote authentication request: 192.168.1.68
[src/device.c:038] Searching for "fuseteam" in the hardware database...
* Authentication device "fuseteam" is connected.
* Performing one time pad verification...
[src/volume.c:097] Searching for volume with uuid 67E3-17ED.
[src/volume.c:121] Found mount points: (null)
[src/volume.c:134] Found volume 67E3-17ED.
[src/volume.c:044] Attempting to mount device /dev/sdb1.
[src/volume.c:056] Mounted device /dev/sdb1 to /media/root/EFI.
[src/pad.c:256] Loading device pad...
[src/pad.c:258] Loading system pad...
[src/pad.c:264] Pad match.
[src/pad.c:153] Checking whether pads are expired or not...
[src/pad.c:182] Pads were generated 721 seconds ago, not updating.
[src/volume.c:183] Attempting to unmount /dev/sdb1 from /media/root/EFI.
[src/volume.c:194] Unmount succeeded.
* Access granted.
```

**Comment by mcdope** [comment]
Welp. such stuff happens where you're too focused. I was so focused on the local check that I've never tested with a device connected, I know where the last one comes from - will be related to a change in return values to be able to distinguish between "unknown" and "known remote".

See, that's why it's good to have beta testers lol.

**Comment by Fuseteam** [comment]
haha yeah it is hehe
lemme see if I can repro and get a w later xD

**Comment by Fuseteam** [comment]
here the w for [the first case](https://github.com/mcdope/pam_usb/issues/51#issuecomment-797659659)
```
 13:50:19 up  5:40,  3 users,  load average: 0.05, 0.09, 0.06
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
tk       tty7     :0               09:23    5:40m  1:07   0.73s dwm
tk       pts/1    192.168.1.68     13:49    2.00s  0.13s  0.06s tmux -2
tk       pts/3    tmux(22064).%1   13:49    2.00s  0.08s  0.01s w
```
and [the second case](https://github.com/mcdope/pam_usb/issues/51#issuecomment-797662229):
```
  13:47:20 up  5:37,  3 users,  load average: 0.17, 0.11, 0.06
USER     TTY      FROM             LOGIN@   IDLE   JCPU   PCPU WHAT
tk       tty7     :0               09:23    5:37m  1:05   0.68s dwm
tk       pts/0    192.168.1.68     13:47    0.00s  1:28   0.00s tmux -u
tk       pts/3    tmux(15794).%1   13:47    0.00s  0.27s  0.20s tmux -u
```

I have managed to reproduce [this](https://github.com/mcdope/pam_usb/issues/51#issuecomment-797545629) as well it appears to be similar to the first case but it only happens once, possibly right after booting

**Comment by mcdope** [comment]
Thanks for the `w`. 

Currently I need to care of my commercial software, plus a family crisis. Soooo, sorry - but I can't work on it for the next few weeks. I will try to free some time for it, but no promises.

**Comment by Fuseteam** [comment]
sure no problem, good luck!

**Comment by mcdope** [comment]
Just a small status update: haven't forgotten this, but still kinda busy. 

In case somebody thinks this issue is critical for him/her: you can use the initial 0.7.3 release and disable `unknown_pts_as_local`.

**Comment by mcdope** [comment]
Heya @Fuseteam !

Guess you thought work would never continue, right? :laughing: But tadaaa - surprise, a new deb for testing: https://www.dropbox.com/s/af1ghfgheyp7cfn/libpam-usb_0.7.4_amd64.deb?dl=0

Please break it ;D The return value issue that you reported last time should be fixed now. Additionally it includes the fix from #59

**Comment by Fuseteam** [comment]
cool~ i knew you'd come through! i deffo try to break it xD

**Comment by mcdope** [comment]
Had you time to check yet? 

I definitely don't want to hurry you considering I took forever with the update XD But would be nice to get this closed.

**Comment by Fuseteam** [comment]
haha true xD i'll try to check today :3

**Comment by Fuseteam** [comment]
seems to work nicely so far :tada:

**Comment by Fuseteam** [comment]
so what i've seen so far is:
locally without byobu authenticates as expected
locally with tmux authenticates as expected
locally with byobu authenticates as expected

remotely without byobu rejects authentication as expected
remote plus start tmux session rejects authentication as expected
remotely with byobu rejects authentication as expected

locally with byobu plus ssh in and attach to the running byobu session also authenticates
locally with tmux plus ssh and attach to the running tmux session also authenticates

to elaborate the last one these are the steps:
- machine#1: open a terminal and launch a byobu/tmux session
- machine#2: ssh into machine#1
- machine#2: run `tmux a` or `byobu` to attach to the session created by step 1
- machine#2: `sudo su`

**Comment by mcdope** [comment]
Hmmm not sure we can catch that, since technically you're authenticating inside a local process then. Could be we end up with a warning in the documentation.

But will try to fix it.

**Comment by Fuseteam** [comment]
Yeah i'm basically connecting to local process in that case 😅

**Comment by mcdope** [comment]
Actually, there is a way to exclude this. But that would also block some legitimate requests maybe.

Could check if the tmux session has further clients attached and as soon as any of them is remote block the access for the whole process. How about that?

**Comment by Fuseteam** [comment]
oh that would block requests as soon as someone attaches to your session, cool
yeah i think that would be a good tradeoff for security, it would also signal someone connected to the session too xD

**Comment by mcdope** [comment]
Yep, that's the idea. Though this is basically a non-issue at this point since abusing this would need the attacked to have the private key to ssh into the account in the first place (if he had the password he would need pam_usb anyway). 

My approach is done, but like always - stuff is trolling me :D 

![grafik](https://user-images.githubusercontent.com/3312979/126233125-296f47b2-1510-4b67-bb47-c9e043b8da7e.png)


Note the green mark in the `who` output, compared to the green marked debug dump what I get in code :D

**Comment by mcdope** [comment]
https://youtu.be/q3svW8PM_jc?t=16

![grafik](https://user-images.githubusercontent.com/3312979/126236376-f7fa572c-b23b-44d4-9c6d-4a40383c3d38.png)

**Comment by mcdope** [comment]
IPv6 still needs testing, for some reason my VM connects only by v4 though my whole network has v6... But for v4 it's already working.

Need to clean up bad naming, ugly output and remove some debugging here and there. But the base is done.

**Comment by Fuseteam** [comment]
Haha thanks man really appreaciate your work on this

**Comment by mcdope** [comment]
![grafik](https://user-images.githubusercontent.com/3312979/126293924-196f2e7a-a0b7-434a-a2e0-4951a491a6be.png)

v6 tested and working, cleaning up now.

**Comment by mcdope** [comment]
Updated signed deb at https://www.dropbox.com/s/af1ghfgheyp7cfn/libpam-usb_0.7.4_amd64.deb?dl=0

**Comment by mcdope** [comment]
Nagnag, please check if you can break it

**Comment by Fuseteam** [comment]
will try to break it tommorow :+1:

**Comment by Fuseteam** [comment]
sorry took me longer to find the time to test. i think having an issue installing the newer version over the old one
if i first open a byobu session then ssh in and connect to the session it works just like before
however i did notice that if first ssh in then start a byobu session and then connect to from the local machine it does fail, i'm not sure if this was the case before

**Comment by mcdope** [comment]
No problem, I'm grateful that you do the tests no matter when :D 

Guess that makes sense, I've tested only with tmux 🤦  When you attach to the session, what's shown in `w` as command? For tux it's `tmux a` i.e. Would save me testing and I could just add the string ^^

**Comment by Fuseteam** [comment]
maybe it might be better for testing if i could ensure i indeed have the correct version i'll try another `apt install --reinstall ./libpamusb.deb` before testing again later

**Comment by mcdope** [comment]
This is what I get with `w` when I've remote client attached to byobu
![image](https://user-images.githubusercontent.com/3312979/127882849-f354bb28-deda-4636-86d8-e457c83bf5a0.png)

could you check how yours look and gimme a screen or copypaste please?

Then I can add the appriate check for it.

**Comment by Fuseteam** [comment]
will do that soon

**Comment by Fuseteam** [comment]
sorry for the delay wanted to make sure it upgraded properly
this is the output of `w` when i connect to a running byobu session remotely
![image](https://user-images.githubusercontent.com/10421851/128044735-03e69836-609e-4f13-b6ab-9f7ce205dc9d.png)

**Comment by Fuseteam** [comment]
just realized your byobu is using screen as the backend while mine uses tmux as the backend :joy:

**Comment by mcdope** [comment]
Interesting, your byobu seems to use tmux as backend, my install uses screen. But I've seen that it can use both. Guess I will need to cover both cases.

Thanks.

**Comment by mcdope** [comment]
Seems the `screen` backend case is handled already lol 

![image](https://user-images.githubusercontent.com/3312979/128732960-928e9dd1-7538-43ce-a821-5654c5d33853.png)

**Comment by mcdope** [comment]
Seems `tmux` backend is fixed too. To cite Britney Spears: Oops I did it again! (Yes, I'm THAT old)

![image](https://user-images.githubusercontent.com/3312979/130125765-717788e1-3db6-4799-a108-efca83733001.png)

Updated deb at the usual link, https://www.dropbox.com/s/af1ghfgheyp7cfn/libpam-usb_0.7.4_amd64.deb?dl=0

**Comment by Fuseteam** [comment]
hmm weird stuff happening here:
![image](https://user-images.githubusercontent.com/10421851/130127142-32c598f3-e6bf-4d32-9e81-d807d707c57a.png)
i only managed to still get through if i do
launch byobu
ssh in from another machine
attach to byobu

i installed with `apt install --reinstall`

**Comment by mcdope** [comment]
I smell a botched `if` again...

**Comment by mcdope** [comment]
Should be fixed, deb is updated again https://www.dropbox.com/s/af1ghfgheyp7cfn/libpam-usb_0.7.4_amd64.deb?dl=0

**Comment by Fuseteam** [comment]
oho~ touché
![image](https://user-images.githubusercontent.com/10421851/130131220-7948330c-7461-4487-b1fb-d9bc91ce8dd2.png)
now just the first case left xD
seems new byobu windows are caught but since the existing one originates from the local user that one passes
![image](https://user-images.githubusercontent.com/10421851/130131179-0885dfc2-bed4-42e4-bfe8-ed39b2fdd093.png)

**Comment by mcdope** [comment]
Yeah, I can see how that happens... That will be easy to fix I guess.

**Comment by Fuseteam** [comment]
cool xD

**Comment by mcdope** [comment]
Since you seem to know byobu and surrounding stuff quite well, could you test this with `new-window` too? Guess that would pass too...

**Comment by Fuseteam** [comment]
oho~ seems to work
![image](https://user-images.githubusercontent.com/10421851/130499973-46e42e7f-bb5c-46ae-a381-a496e87cd227.png)

**Comment by mcdope** [comment]
lmao i literally opened the issue right as you commented, nice :D

**Comment by Fuseteam** [comment]
great timing xDDD

**Comment by mcdope** [comment]
if you still find a way to break it before 29. August 23:59 we should start talking about bug bounties, else it will be released after that datetime.

**Comment by Fuseteam** [comment]
so far so good, awesome work :+1:

**Comment by Fuseteam** [comment]
heh so far so good

**Comment by mcdope** [comment]
Let's leave it open for now, since the fix is not merged yet. I still need to clean some stuff in the PR up before merging, issue will be autoclosed by merge then.

**Comment by mcdope** [comment]
Released as v0.8.0

**Comment by Fuseteam** [comment]
wooohooo thanks :+1:
