### ISSUE TITLE
I tried running pamusb-conf and I got the error below.

### ISSUE THREAD

**Issue by PwnBoi79** [mcdope/pam_usb#52]
Traceback (most recent call last):
  File "/usr/bin/pamusb-conf", line 20, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'

What do I do now?

**Comment by mcdope** [comment]
You're missing `python3-gi` - which is missing from the requirements list for manual install, will fix that.

**Comment by mcdope** [comment]
Wiki is corrected.

**Comment by PwnBoi79** [comment]
I have python3-gi installed but I'm still getting that error

**Comment by mcdope** [comment]
No you haven't - or it isn't installed properly. The message clearly says so.
